package com.lifebrief_backend.app.entity;

import java.util.Set;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Lob;

@Entity
public class Profile {

    @Id
    @Column(name = "profile_id", columnDefinition = "CHAR(36)")
    private String profileId;  // UUID generated by MySQL

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false)
    private String password;

    private String city;
    private String state;
    private String country;
    private Integer age;
    private Double weight;

    @Enumerated(EnumType.STRING)
    @Column(name = "food_preference")
    private FoodPreference foodPreference;

    @Lob
    @Column(name = "health_problems")
    private String healthProblems;

    @Lob
    @Column(name = "food_allergies")
    private String foodAllergies;

    // Represent the SET('Monday',...,'Sunday') as a collection of strings
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "profile_days", joinColumns = @JoinColumn(name = "profile_id"))
    @Column(name = "day")
    private Set<String> daysNonVeg;

    public Profile() {}

    // --- Getters and Setters ---
    public String getProfileId() {
        return profileId;
    }

    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public FoodPreference getFoodPreference() {
        return foodPreference;
    }

    public void setFoodPreference(FoodPreference foodPreference) {
        this.foodPreference = foodPreference;
    }

    public String getHealthProblems() {
        return healthProblems;
    }

    public void setHealthProblems(String healthProblems) {
        this.healthProblems = healthProblems;
    }

    public String getFoodAllergies() {
        return foodAllergies;
    }

    public void setFoodAllergies(String foodAllergies) {
        this.foodAllergies = foodAllergies;
    }

    public Set<String> getDaysNonVeg() {
        return daysNonVeg;
    }

    public void setDaysNonVeg(Set<String> daysNonVeg) {
        this.daysNonVeg = daysNonVeg;
    }
}